name: fwfh_url_launcher
version: 0.6.1+3
description: WidgetFactory extension to launch A tag via url_launcher plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html
environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html_core:
    git:
      url: https://github.com/vtsindia-dev/flutter_widget_from_html_core.git
  url_launcher: ^6.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any
